//vehicle type

export const CREATE_VEHICLE_TYPE_REQUEST = "CREATE_VEHICLE_TYPE_REQUEST";
export const CREATE_VEHICLE_TYPE_SUCCESS = "CREATE_VEHICLE_TYPE_SUCCESS";
export const CREATE_VEHICLE_TYPE_FAILURE = "CREATE_VEHICLE_TYPE_FAILURE";

export const VEHICLE_TYPE_LIST_REQUEST = "VEHICLE_TYPE_LIST_REQUEST";
export const VEHICLE_TYPE_LIST_SUCCESS = "VEHICLE_TYPE_LIST_SUCCESS";
export const VEHICLE_TYPE_LIST_FAIL = "VEHICLE_TYPE_LIST_FAIL";
export const VEHICLE_TYPE_LIST_RESET = "VEHICLE_TYPE_LIST_RESET";

//vehicle
export const VEHICLE_REGISTER_REQUEST = "VEHICLE_REGISTER_REQUEST";
export const VEHICLE_REGISTER_SUCCESS = "VEHICLE_REGISTER_SUCCESS";
export const VEHICLE_REGISTER_FAIL = "VEHICLE_REGISTER_FAIL";

export const GET_VEHICLE_REQUEST = "GET_VEHICLE_REQUEST";
export const GET_VEHICLE_SUCCESS = "GET_VEHICLE_SUCCESS";
export const GET_VEHICLE_FAIL = "GET_VEHICLE_FAIL";
export const GET_VEHICLE_RESET = "GET_VEHICLE_RESET";

// bookingTypes.js
export const FETCH_BOOKING_HISTORY = "FETCH_BOOKING_HISTORY";
export const FETCH_BOOKING_HISTORY_SUCCESS = "FETCH_BOOKING_HISTORY_SUCCESS";
export const FETCH_BOOKING_HISTORY_FAILURE = "FETCH_BOOKING_HISTORY_FAILURE";

