
//District
export const GET_DISTRICTS_REQUEST = "GET_DISTRICTS_REQUEST";
export const GET_DISTRICTS_SUCCESS = "GET_DISTRICTS_SUCCESS";
export const GET_DISTRICTS_FAIL = "GET_DISTRICTS_FAIL";

export const CREATE_DISTRICT_REQUEST = "CREATE_DISTRICT_REQUEST";
export const CREATE_DISTRICT_SUCCESS = "CREATE_DISTRICT_SUCCESS";
export const CREATE_DISTRICT_FAIL = "CREATE_DISTRICT_FAIL";

export const UPDATE_DISTRICT_REQUEST = "UPDATE_DISTRICT_REQUEST";
export const UPDATE_DISTRICT_SUCCESS = "UPDATE_DISTRICT_SUCCESS";
export const UPDATE_DISTRICT_FAIL = "UPDATE_DISTRICT_FAIL";

export const DELETE_DISTRICT_REQUEST = "DELETE_DISTRICT_REQUEST";
export const DELETE_DISTRICT_SUCCESS = "DELETE_DISTRICT_SUCCESS";
export const DELETE_DISTRICT_FAIL = "DELETE_DISTRICT_FAIL";

// Taluka
export const GET_TALUKAS_REQUEST = "GET_TALUKAS_REQUEST";
export const GET_TALUKAS_SUCCESS = "GET_TALUKAS_SUCCESS";
export const GET_TALUKAS_FAIL = "GET_TALUKAS_FAIL";

export const CREATE_TALUKA_REQUEST = "CREATE_TALUKA_REQUEST";
export const CREATE_TALUKA_SUCCESS = "CREATE_TALUKA_SUCCESS";
export const CREATE_TALUKA_FAIL = "CREATE_TALUKA_FAIL";

export const UPDATE_TALUKA_REQUEST = "UPDATE_TALUKA_REQUEST";
export const UPDATE_TALUKA_SUCCESS = "UPDATE_TALUKA_SUCCESS";
export const UPDATE_TALUKA_FAIL = "UPDATE_TALUKA_FAIL";

export const DELETE_TALUKA_REQUEST = "DELETE_TALUKA_REQUEST";
export const DELETE_TALUKA_SUCCESS = "DELETE_TALUKA_SUCCESS";
export const DELETE_TALUKA_FAIL = "DELETE_TALUKA_FAIL";

// Village
export const GET_VILLAGES_REQUEST = "GET_VILLAGES_REQUEST";
export const GET_VILLAGES_SUCCESS = "GET_VILLAGES_SUCCESS";
export const GET_VILLAGES_FAIL = "GET_VILLAGES_FAIL";

export const CREATE_VILLAGE_REQUEST = "CREATE_VILLAGE_REQUEST";
export const CREATE_VILLAGE_SUCCESS = "CREATE_VILLAGE_SUCCESS";
export const CREATE_VILLAGE_FAIL = "CREATE_VILLAGE_FAIL";

export const UPDATE_VILLAGE_REQUEST = "UPDATE_VILLAGE_REQUEST";
export const UPDATE_VILLAGE_SUCCESS = "UPDATE_VILLAGE_SUCCESS";
export const UPDATE_VILLAGE_FAIL = "UPDATE_VILLAGE_FAIL";

export const DELETE_VILLAGE_REQUEST = "DELETE_VILLAGE_REQUEST";
export const DELETE_VILLAGE_SUCCESS = "DELETE_VILLAGE_SUCCESS";
export const DELETE_VILLAGE_FAIL = "DELETE_VILLAGE_FAIL";


//Approval users
export const FETCH_PENDING_USERS_REQUEST = "FETCH_PENDING_USERS_REQUEST";
export const FETCH_PENDING_USERS_SUCCESS = "FETCH_PENDING_USERS_SUCCESS";
export const FETCH_PENDING_USERS_FAILURE = "FETCH_PENDING_USERS_FAILURE";

export const UPDATE_USER_STATUS_REQUEST = "UPDATE_USER_STATUS_REQUEST";
export const UPDATE_USER_STATUS_SUCCESS = "UPDATE_USER_STATUS_SUCCESS";
export const UPDATE_USER_STATUS_FAILURE = "UPDATE_USER_STATUS_FAILURE";

// user list
export const ROLE_LIST_REQUEST = "ROLE_LIST_REQUEST";
export const ROLE_LIST_SUCCESS = "ROLE_LIST_SUCCESS";
export const ROLE_LIST_FAIL = "ROLE_LIST_FAIL";