
//District
export const GET_DISTRICTS_REQUEST = "GET_DISTRICTS_REQUEST";
export const GET_DISTRICTS_SUCCESS = "GET_DISTRICTS_SUCCESS";
export const GET_DISTRICTS_FAIL = "GET_DISTRICTS_FAIL";

export const CREATE_DISTRICT_REQUEST = "CREATE_DISTRICT_REQUEST";
export const CREATE_DISTRICT_SUCCESS = "CREATE_DISTRICT_SUCCESS";
export const CREATE_DISTRICT_FAIL = "CREATE_DISTRICT_FAIL";

export const UPDATE_DISTRICT_REQUEST = "UPDATE_DISTRICT_REQUEST";
export const UPDATE_DISTRICT_SUCCESS = "UPDATE_DISTRICT_SUCCESS";
export const UPDATE_DISTRICT_FAIL = "UPDATE_DISTRICT_FAIL";

export const DELETE_DISTRICT_REQUEST = "DELETE_DISTRICT_REQUEST";
export const DELETE_DISTRICT_SUCCESS = "DELETE_DISTRICT_SUCCESS";
export const DELETE_DISTRICT_FAIL = "DELETE_DISTRICT_FAIL";

// Taluka
export const GET_TALUKAS_REQUEST = "GET_TALUKAS_REQUEST";
export const GET_TALUKAS_SUCCESS = "GET_TALUKAS_SUCCESS";
export const GET_TALUKAS_FAIL = "GET_TALUKAS_FAIL";

export const CREATE_TALUKA_REQUEST = "CREATE_TALUKA_REQUEST";
export const CREATE_TALUKA_SUCCESS = "CREATE_TALUKA_SUCCESS";
export const CREATE_TALUKA_FAIL = "CREATE_TALUKA_FAIL";

export const UPDATE_TALUKA_REQUEST = "UPDATE_TALUKA_REQUEST";
export const UPDATE_TALUKA_SUCCESS = "UPDATE_TALUKA_SUCCESS";
export const UPDATE_TALUKA_FAIL = "UPDATE_TALUKA_FAIL";

export const DELETE_TALUKA_REQUEST = "DELETE_TALUKA_REQUEST";
export const DELETE_TALUKA_SUCCESS = "DELETE_TALUKA_SUCCESS";
export const DELETE_TALUKA_FAIL = "DELETE_TALUKA_FAIL";

// Village
export const GET_VILLAGES_REQUEST = "GET_VILLAGES_REQUEST";
export const GET_VILLAGES_SUCCESS = "GET_VILLAGES_SUCCESS";
export const GET_VILLAGES_FAIL = "GET_VILLAGES_FAIL";

export const CREATE_VILLAGE_REQUEST = "CREATE_VILLAGE_REQUEST";
export const CREATE_VILLAGE_SUCCESS = "CREATE_VILLAGE_SUCCESS";
export const CREATE_VILLAGE_FAIL = "CREATE_VILLAGE_FAIL";

export const UPDATE_VILLAGE_REQUEST = "UPDATE_VILLAGE_REQUEST";
export const UPDATE_VILLAGE_SUCCESS = "UPDATE_VILLAGE_SUCCESS";
export const UPDATE_VILLAGE_FAIL = "UPDATE_VILLAGE_FAIL";

export const DELETE_VILLAGE_REQUEST = "DELETE_VILLAGE_REQUEST";
export const DELETE_VILLAGE_SUCCESS = "DELETE_VILLAGE_SUCCESS";
export const DELETE_VILLAGE_FAIL = "DELETE_VILLAGE_FAIL";


//Approval users
export const FETCH_PENDING_USERS_REQUEST = "FETCH_PENDING_USERS_REQUEST";
export const FETCH_PENDING_USERS_SUCCESS = "FETCH_PENDING_USERS_SUCCESS";
export const FETCH_PENDING_USERS_FAILURE = "FETCH_PENDING_USERS_FAILURE";

export const UPDATE_USER_STATUS_REQUEST = "UPDATE_USER_STATUS_REQUEST";
export const UPDATE_USER_STATUS_SUCCESS = "UPDATE_USER_STATUS_SUCCESS";
export const UPDATE_USER_STATUS_FAILURE = "UPDATE_USER_STATUS_FAILURE";

// user list
export const ROLE_LIST_REQUEST = "ROLE_LIST_REQUEST";
export const ROLE_LIST_SUCCESS = "ROLE_LIST_SUCCESS";
export const ROLE_LIST_FAIL = "ROLE_LIST_FAIL";

//filter driver on location
export const FILTER_DRIVERS_REQUEST = 'FILTER_DRIVERS_REQUEST';
export const FILTER_DRIVERS_SUCCESS = 'FILTER_DRIVERS_SUCCESS';
export const FILTER_DRIVERS_FAIL = 'FILTER_DRIVERS_FAIL';
export const FILTER_DRIVERS_RESET = 'FILTER_DRIVERS_RESET';
//filter member on location
export const FILTER_MEMBER_REQUEST = 'FILTER_MEMBER_REQUEST';
export const FILTER_MEMBER_SUCCESS = 'FILTER_MEMBER_SUCCESS';
export const FILTER_MEMBER_FAIL = 'FILTER_MEMBER_FAIL';
export const FILTER_MEMBER_RESET = 'FILTER_MEMBER_RESET';
// Vehicle filter list
export const FILTER_VEHICLES_REQUEST = "FILTER_VEHICLES_REQUEST";
export const FILTER_VEHICLES_SUCCESS = "FILTER_VEHICLES_SUCCESS";
export const FILTER_VEHICLES_FAIL = "FILTER_VEHICLES_FAIL";
export const FILTER_VEHICLES_RESET = "FILTER_VEHICLES_RESET";
//booking
export const BOOKING_CREATE_REQUEST = 'BOOKING_CREATE_REQUEST';
export const BOOKING_CREATE_SUCCESS = 'BOOKING_CREATE_SUCCESS';
export const BOOKING_CREATE_FAIL = 'BOOKING_CREATE_FAIL';

export const ASSIGN_VEHICLE_REQUEST = "ASSIGN_VEHICLE_REQUEST";
export const ASSIGN_VEHICLE_SUCCESS = "ASSIGN_VEHICLE_SUCCESS";
export const ASSIGN_VEHICLE_FAIL = "ASSIGN_VEHICLE_FAIL";

export const ASSIGN_DRIVER_REQUEST = "ASSIGN_DRIVER_REQUEST";
export const ASSIGN_DRIVER_SUCCESS = "ASSIGN_DRIVER_SUCCESS";
export const ASSIGN_DRIVER_FAIL = "ASSIGN_DRIVER_FAIL";

export const FETCH_BOOKINGS_REQUEST = "FETCH_BOOKINGS_REQUEST";
export const FETCH_BOOKINGS_SUCCESS = "FETCH_BOOKINGS_SUCCESS";
export const FETCH_BOOKINGS_FAIL = "FETCH_BOOKINGS_FAIL";


// Gat Adhikari Action Types
export const FETCH_GAT_ADHIKARI_REQUEST = "FETCH_GAT_ADHIKARI_REQUEST";
export const FETCH_GAT_ADHIKARI_SUCCESS = "FETCH_GAT_ADHIKARI_SUCCESS";
export const FETCH_GAT_ADHIKARI_FAILURE = "FETCH_GAT_ADHIKARI_FAILURE";

export const ASSIGN_GAT_ADHIKARI_REQUEST = "ASSIGN_GAT_ADHIKARI_REQUEST";
export const ASSIGN_GAT_ADHIKARI_SUCCESS = "ASSIGN_GAT_ADHIKARI_SUCCESS";
export const ASSIGN_GAT_ADHIKARI_FAILURE = "ASSIGN_GAT_ADHIKARI_FAILURE";


// Get vendor action types 
export const FETCH_VENDOR_LIST_REQUEST = "FETCH_VENDOR_LIST_REQUEST";
export const FETCH_VENDOR_LIST_SUCCESS = "FETCH_VENDOR_LIST_SUCCESS";
export const FETCH_VENDOR_LIST_FAILURE = "FETCH_VENDOR_LIST_FAILURE";

// Get member action types 
export const FETCH_MEMBER_LIST_REQUEST = "FETCH_MEMBER_LIST_REQUEST";
export const FETCH_MEMBER_LIST_SUCCESS = "FETCH_MEMBER_LIST_SUCCESS";
export const FETCH_MEMBER_LIST_FAILURE = "FETCH_MEMBER_LIST_FAILURE";

// Get driver action types 
export const FETCH_DRIVER_LIST_REQUEST = "FETCH_DRIVER_LIST_REQUEST";
export const FETCH_DRIVER_LIST_SUCCESS = "FETCH_DRIVER_LIST_SUCCESS";
export const FETCH_DRIVER_LIST_FAILURE = "FETCH_DRIVER_LIST_FAILURE";
// get all lists
export const FETCH_ALL_LIST_REQUEST = "FETCH_ALL_LIST_REQUEST";
export const FETCH_ALL_LIST_SUCCESS = "FETCH_ALL_LIST_SUCCESS";
export const FETCH_ALL_LIST_FAILURE = "FETCH_ALL_LIST_FAILURE";

// Admin DRIVER status change 
export const DRIVER_STATUS_REQUEST = "DRIVER_STATUS_REQUEST";
export const DRIVER_STATUS_SUCCESS = "DRIVER_STATUS_SUCCESS";
export const DRIVER_STATUS_FAILURE = "DRIVER_STATUS_FAILURE";

// Member status change
export const MEMBER_STATUS_REQUEST = "MEMBER_STATUS_REQUEST";
export const MEMBER_STATUS_SUCCESS = "MEMBER_STATUS_SUCCESS";
export const MEMBER_STATUS_FAILURE = "MEMBER_STATUS_FAILURE";

// Vendor status change
export const VENDOR_STATUS_REQUEST = "VENDOR_STATUS_REQUEST";
export const VENDOR_STATUS_SUCCESS = "VENDOR_STATUS_SUCCESS";
export const VENDOR_STATUS_FAILURE = "VENDOR_STATUS_FAILURE";
