// DRIVER COMPLAINTS
export const CREATE_COMPLAINT_REQUEST = "CREATE_COMPLAINT_REQUEST";
export const CREATE_COMPLAINT_SUCCESS = "CREATE_COMPLAINT_SUCCESS";
export const CREATE_COMPLAINT_FAIL = "CREATE_COMPLAINT_FAIL";