// DRIVER COMPLAINTS
export const CREATE_COMPLAINT_REQUEST = "CREATE_COMPLAINT_REQUEST";
export const CREATE_COMPLAINT_SUCCESS = "CREATE_COMPLAINT_SUCCESS";
export const CREATE_COMPLAINT_FAIL = "CREATE_COMPLAINT_FAIL";

export const CREATE_DRIVER_USAGE_LOG_REQUEST = "CREATE_DRIVER_USAGE_LOG_REQUEST";
export const CREATE_DRIVER_USAGE_LOG_SUCCESS = "CREATE_DRIVER_USAGE_LOG_SUCCESS";
export const CREATE_DRIVER_USAGE_LOG_FAIL = "CREATE_DRIVER_USAGE_LOG_FAIL";

export const LIST_DRIVER_USAGE_LOG_REQUEST = "LIST_DRIVER_USAGE_LOG_REQUEST";
export const LIST_DRIVER_USAGE_LOG_SUCCESS = "LIST_DRIVER_USAGE_LOG_SUCCESS";
export const LIST_DRIVER_USAGE_LOG_FAIL = "LIST_DRIVER_USAGE_LOG_FAIL";

export const DETAIL_DRIVER_USAGE_LOG_REQUEST = "DETAIL_DRIVER_USAGE_LOG_REQUEST";
export const DETAIL_DRIVER_USAGE_LOG_SUCCESS = "DETAIL_DRIVER_USAGE_LOG_SUCCESS";
export const DETAIL_DRIVER_USAGE_LOG_FAIL = "DETAIL_DRIVER_USAGE_LOG_FAIL";

export const COMPLETE_DRIVER_USAGE_LOG_REQUEST = "COMPLETE_DRIVER_USAGE_LOG_REQUEST";
export const COMPLETE_DRIVER_USAGE_LOG_SUCCESS = "COMPLETE_DRIVER_USAGE_LOG_SUCCESS";
export const COMPLETE_DRIVER_USAGE_LOG_FAIL = "COMPLETE_DRIVER_USAGE_LOG_FAIL";

export const LIST_ALL_BOOKINGS_REQUEST = "LIST_ALL_BOOKINGS_REQUEST";
export const LIST_ALL_BOOKINGS_SUCCESS = "LIST_ALL_BOOKINGS_SUCCESS";
export const LIST_ALL_BOOKINGS_FAIL = "LIST_ALL_BOOKINGS_FAIL";

export const DRIVER_BREAK_REQUEST = "DRIVER_BREAK_REQUEST";
export const DRIVER_BREAK_SUCCESS = "DRIVER_BREAK_SUCCESS";
export const DRIVER_BREAK_FAIL = "DRIVER_BREAK_FAIL";
