// super user login
export const SULOGIN_REQUEST = "LOGIN_REQUEST";
export const SULOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SULOGIN_FAILED = "LOGIN_FAILED";
export const SULOGOUT = "LOGOUT";

// login for admin and all other users
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";

//ADMIN
//verify email
export const CHECK_EMAIL_REQUEST   = 'CHECK_EMAIL_REQUEST';
export const CHECK_EMAIL_SUCCESS   = 'CHECK_EMAIL_SUCCESS';
export const CHECK_EMAIL_FAILURE   = 'CHECK_EMAIL_FAILURE';
// register
export const ADMINREGISTER_REQUEST = 'ADMINREGISTER_REQUEST';
export const ADMINREGISTER_SUCCESS = 'ADMINREGISTER_SUCCESS';
export const ADMINREGISTER_FAILURE = 'ADMINREGISTER_FAILURE';

//ALL USER
//check email
export const USER_CHECK_EMAIL_REQUEST   = 'CHECK_EMAIL_REQUEST';
export const USER_CHECK_EMAIL_SUCCESS   = 'CHECK_EMAIL_SUCCESS';
export const USER_CHECK_EMAIL_FAILURE   = 'CHECK_EMAIL_FAILURE';
//verify email
export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE";
//register
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
//get
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";
//get count
export const GET_USER_COUNT_REQUEST = "GET_USER_COUNT_REQUEST";
export const GET_USER_COUNT_SUCCESS = "GET_USER_COUNT_SUCCESS";
export const GET_USER_COUNT_FAIL = "GET_USER_COUNT_FAIL";
//update
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
//delete
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
