export const BOOKING_LIST_REQUEST = 'BOOKING_LIST_REQUEST';
export const BOOKING_LIST_SUCCESS = 'BOOKING_LIST_SUCCESS';
export const BOOKING_LIST_FAIL = 'BOOKING_LIST_FAIL';

export const BOOKING_CREATE_REQUEST = 'BOOKING_CREATE_REQUEST';
export const BOOKING_CREATE_SUCCESS = 'BOOKING_CREATE_SUCCESS';
export const BOOKING_CREATE_FAIL = 'BOOKING_CREATE_FAIL';

export const CREATE_COMPLAINT_REQUEST = "CREATE_COMPLAINT_REQUEST";
export const CREATE_COMPLAINT_SUCCESS = "CREATE_COMPLAINT_SUCCESS";
export const CREATE_COMPLAINT_FAIL = "CREATE_COMPLAINT_FAIL";

