// GatAdhikari Members
export const FETCH_GA_MEMBERS_REQUEST = "FETCH_GA_MEMBERS_REQUEST";
export const FETCH_GA_MEMBERS_SUCCESS = "FETCH_GA_MEMBERS_SUCCESS";
export const FETCH_GA_MEMBERS_FAILURE = "FETCH_GA_MEMBERS_FAILURE";

// GatAdhikari Members Bookings
export const FETCH_GA_MEMBER_BOOKINGS_REQUEST = "FETCH_GA_MEMBER_BOOKINGS_REQUEST";
export const FETCH_GA_MEMBER_BOOKINGS_SUCCESS = "FETCH_GA_MEMBER_BOOKINGS_SUCCESS";
export const FETCH_GA_MEMBER_BOOKINGS_FAILURE = "FETCH_GA_MEMBER_BOOKINGS_FAILURE";
